name: CI
# This workflow is triggered on pushes & pull requests
on: [pull_request, push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/packagrio/packagr:latest-golang
    # Service containers to run with `build` (Required for end-to-end testing)
    steps:
      - name: Git
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository ppa:git-core/ppa && apt-get update && apt-get install -y git
          git --version
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          go test -v -tags "static" ./...
      - name: Build Binaries
        run: |
          GOOS=darwin GOARCH=amd64 go build -buildvcs=false -ldflags "-X main.goos=darwin -X main.goarch=amd64" -o checkr-darwin-amd64 -tags "static" cmd/checkr/checkr.go
          chmod +x checkr-darwin-amd64
          GOOS=linux GOARCH=amd64 go build -buildvcs=false -ldflags "-X main.goos=linux -X main.goarch=amd64" -o checkr-linux-amd64 -tags "static" cmd/checkr/checkr.go
          chmod +x checkr-linux-amd64
          GOOS=windows GOARCH=amd64 go build -buildvcs=false -ldflags "-X main.goos=windows -X main.goarch=amd64" -o checkr-windows-amd64.exe -tags "static" cmd/checkr/checkr.go
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: binaries.zip
          path: |
            checkr-*
