name: Release
# This workflow is triggered manually
on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: 'Version Bump Type (major, minor, patch)'
        required: true
        default: 'patch'
      version_metadata_path:
        description: 'Path to file containing Version string'
        required: true
        default: 'pkg/version/version.go'


jobs:
  release:
    name: Create Release Commit
    runs-on: ubuntu-latest
    container: ghcr.io/packagrio/packagr:latest-golang
    env:
      STATIC: true
    steps:
      - name: Get Packagr Token
        id: packagr-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.PACKAGR_APP_ID }}
          private_key: ${{ secrets.PACKAGR_APP_PRIVATE_KEY }}
      - name: Git
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository ppa:git-core/ppa && apt-get update && apt-get install -y git
          git --version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version
        id: bump_version
        uses: packagrio/action-bumpr-go@master
        with:
          version_bump_type: ${{ github.event.inputs.version_bump_type }}
          version_metadata_path: ${{ github.event.inputs.version_metadata_path }}
        env:
          GITHUB_TOKEN: ${{ steps.packagr-token.outputs.token }}
      - name: Test
        run: |
          go test -v -tags "static" ./...
      - name: Build Binaries
        run: |
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.goos=darwin -X main.goarch=amd64" -o checkr-darwin-amd64 -tags "static" $(go list ./cmd/...)
          chmod +x checkr-darwin-amd64
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.goos=linux -X main.goarch=amd64" -o checkr-linux-amd64 -tags "static" $(go list ./cmd/...)
          chmod +x checkr-linux-amd64
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.goos=windows -X main.goarch=amd64" -o checkr-windows-amd64.exe -tags "static" $(go list ./cmd/...)

      - name: Commit Changes Locally
        id: commit
        uses: packagrio/action-releasr-go@master
        env:
          GITHUB_TOKEN: ${{ steps.packagr-token.outputs.token }}
        with:
          version_metadata_path: ${{ github.event.inputs.version_metadata_path }}
      - name: Publish Release & Assets
        id: publish
        uses: packagrio/action-publishr-go@master
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ steps.packagr-token.outputs.token }}
        with:
          version_metadata_path: ${{ github.event.inputs.version_metadata_path }}
          upload_assets:
            checkr-darwin-amd64
            checkr-linux-amd64
            checkr-windows-amd64.exe
